In [1]:
import torch
from torch import nn

In [11]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.flatten = nn.Flatten()
    self.linear_seq_stack = nn.Sequential(
        nn.Linear(5,3),
        nn.ReLU(),
        nn.Linear(3,4),
    )

  def forward(self,x):
    x = self.flatten(x)
    logits = self.linear_seq_stack(x)
    return logits

In [12]:
model = NeuralNetwork()
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_seq_stack): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=4, bias=True)
  )
)


In [13]:
data = torch.rand(1,5)
data

tensor([[0.5506, 0.8568, 0.9278, 0.4081, 0.3274]])

In [14]:
logits = model(data)
logits

tensor([[ 0.3301,  0.1453, -0.4958, -0.2990]], grad_fn=<AddmmBackward0>)

In [26]:
pred_prob = nn.Softmax(dim = 1)(logits)
type(pred_prob)
print(pred_prob)

tensor([[0.3569, 0.2966, 0.1563, 0.1902]], grad_fn=<SoftmaxBackward0>)


In [25]:
prediction = pred_prob.argmax()
print(prediction)

tensor(0)
