In [35]:
import torch
import numpy as np

torch.seed
a = torch.randint(0,3,(2,5))
print(a)
torch.einsum("ij->ji",a)

tensor([[1, 2, 1, 1, 1],
        [0, 1, 2, 0, 0]])


tensor([[1, 0],
        [2, 1],
        [1, 2],
        [1, 0],
        [1, 0]])

In [36]:
#sum of all elements
torch.einsum("ij->",a)

tensor(9)

In [37]:
#column-wise sum

torch.einsum("ij->j",a)

tensor([1, 3, 3, 1, 1])

In [38]:
# row-wise sum
torch.einsum("ij->i",a)

tensor([6, 3])

In [42]:
# matrix-vector multplication
v = torch.randint(3,(1,5))
torch.einsum("ij,kj->ik",a,v)

tensor([[4],
        [4]])

In [44]:
#matrix-matrix multiplication
torch.einsum("ij,kj->ik",a,a)

tensor([[8, 4],
        [4, 5]])

In [49]:
#dot product of first row with first row
torch.einsum("i,i->",a[0],a[0])

tensor(8)

In [50]:
#dot product matrix
torch.einsum("ij,ij->", a,a)

tensor(13)

In [51]:
#hadamard product ( element wise multiplication )
torch.einsum("ij,ij->ij",a,a)

tensor([[1, 4, 1, 1, 1],
        [0, 1, 4, 0, 0]])

In [55]:
# batch-matrix multiplication
x = torch.rand((3,2,5))
y = torch.rand((3,5,3))

res = torch.einsum("ijk,ikl->ijl",x,y)
res.shape

torch.Size([3, 2, 3])

In [62]:
# finding the matrix diagonal
U = torch.rand((4,4))
print(U)
torch.einsum("ii->i",U)

tensor([[0.2011, 0.6229, 0.5224, 0.7296],
        [0.2219, 0.9845, 0.7490, 0.3138],
        [0.6340, 0.0017, 0.9302, 0.7017],
        [0.2823, 0.6925, 0.3987, 0.6126]])


tensor([0.2011, 0.9845, 0.9302, 0.6126])

In [63]:
# matrix trace
torch.einsum("ii->", U)

tensor(2.7285)