Pytorch Fundamentals 00

In [1]:
import torch
torch.__version__

'1.13.1+cu116'

Tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#vector or one dimensional tensor
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,5],
                       [8,6]])
MATRIX

tensor([[7, 5],
        [8, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR.ndim

3

In [14]:
#how to create a random tensor using torch.rand( size= () )
random_tensor = torch.rand( size = (5,6))
random_tensor , random_tensor.dtype

(tensor([[0.2360, 0.7725, 0.1363, 0.6899, 0.2170, 0.1404],
         [0.8411, 0.3813, 0.4999, 0.6925, 0.7163, 0.8900],
         [0.5383, 0.7317, 0.8255, 0.1512, 0.6433, 0.8974],
         [0.5191, 0.6064, 0.8450, 0.8317, 0.1669, 0.1159],
         [0.9825, 0.9716, 0.8934, 0.3880, 0.9370, 0.6026]]), torch.float32)

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
#all zeros tensor 
zero_tensor = torch.zeros(size = (3,4))
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
#tensor in a range
zero_to_ten = torch.arange(start = 0, end = 10 , step = 2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [18]:
#tensor like zero
like_tensor = torch.zeros_like(zero_to_ten)
like_tensor

tensor([0, 0, 0, 0, 0])

In [19]:
#tensor like ones
like_tensor_one = torch.ones_like(zero_to_ten)
like_tensor_one

tensor([1, 1, 1, 1, 1])

Tensor data type is all to do with precision and also to do with computation.

If tensor is float 8 , then the precison is less and computation is easy

If tensor is float 64 , then the precision is more and computation is more 

If tensor is default , it is torch.float32


In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
#now making tensor of float 16
float_16_tensor = torch.tensor([3.0 , 6.0, 9.0] , dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [22]:
#information which is common in tensorflow
some_tensor = torch.rand(size = (3,4))
print(some_tensor)

print("shape {} ".format(some_tensor.shape))
print("Datatype {} ".format(some_tensor.dtype))
print("Device of the tensor {} ".format(some_tensor.device))


tensor([[0.2751, 0.6064, 0.7091, 0.3606],
        [0.2491, 0.8637, 0.1252, 0.3206],
        [0.5262, 0.0395, 0.0208, 0.3487]])
shape torch.Size([3, 4]) 
Datatype torch.float32 
Device of the tensor cpu 


In [23]:
#mostly these are the only issues that come in tensor computation - shape ,dtype,device

Operations
addition
subtraction
multiplication , element wise
division
matrix multiplication

In [24]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [25]:
tensor + 10

tensor([11, 12, 13])

In [26]:
tensor - 1

tensor([0, 1, 2])

In [27]:
#tensor remains unchanged
tensor

tensor([1, 2, 3])

In [28]:
#tensor when reassigned then get changed
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [29]:
tensor

tensor([11, 12, 13])

In [30]:
torch.multiply(tensor , 10)

tensor([110, 120, 130])

In [31]:
#tensor gets changed
tensor

tensor([11, 12, 13])

In [32]:
#element wise multiplication
torch.multiply(tensor , tensor)

tensor([121, 144, 169])

In [34]:
#matrix multiplication
#1st way 
tensor = torch.tensor([1,2,3])
tensor @ tensor

tensor(14)

In [40]:
#2nd way using matmul of torch
torch.matmul(tensor , tensor)

tensor(14)

In [48]:
#dealing with shape errors in tensorflow

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype = torch.float32)

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]], dtype = torch.float32)

In [49]:
#shape of both the tensors
print(tensor_A.shape)
print(tensor_B.shape)


torch.Size([3, 2])
torch.Size([3, 2])


In [51]:
#both have the second element that does not match so we will have to transpose the
#one of the vectors so that the dimensions match and we can perform matrix multiplication

resultant_tensor = torch.matmul(tensor_A , tensor_B.T) #no error 
#torch.matmul(tensor_A , tensor_B) #error

In [53]:
print(tensor_A.shape)
print(tensor_B.T.shape)
print(resultant_tensor.shape)

torch.Size([3, 2])
torch.Size([2, 3])
torch.Size([3, 3])


In [54]:
torch.mm(tensor_A , tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [59]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [61]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

RuntimeError: ignored

In [62]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
y = tensor_A.T
output = linear(y)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


In [65]:
#Aggregation function on tensors
#first lets declare a tensor
tensor = torch.arange(0,100,10)
#max min mean sum

max_val = torch.max(tensor)
min_val = torch.min(tensor)
mean_val = torch.mean(tensor)
sum_val = torch.sum(tensor)

print(max_val)
print(min_val)
print(mean_val)
print(sum_val)

RuntimeError: ignored

In [66]:
#Aggregation function on tensors
#first lets declare a tensor
tensor = torch.arange(0,100,10)
#max min mean sum

max_val = torch.max(tensor)
min_val = torch.min(tensor)
mean_val = torch.mean(tensor.type(torch.float32))
sum_val = torch.sum(tensor)

print(max_val)
print(min_val)
print(mean_val)
print(sum_val)

tensor(90)
tensor(0)
tensor(45.)
tensor(450)


In [70]:
#positional arguments
print(tensor)
print(tensor.argmax())
print(tensor.argmin())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(9)
tensor(0)


In [75]:
#changing the datatype
tensor.dtype

torch.float64

In [76]:
tensor_64 = tensor.type(torch.float64)
print(tensor.dtype)

torch.float64


In [78]:
#reshaping
test_tensor = torch.arange(1. , 7.)

In [79]:
test_tensor.shape

torch.Size([6])

In [83]:
test_tensor_reshape = test_tensor.reshape(2,3)
print(test_tensor_reshape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [1]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [86]:
#indexing of tensors (i found it interesting and a litte tough , so dimensions are a little bit tough topic)
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [87]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [88]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [89]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [3]:
import numpy as np
import torch

In [9]:
array = np.random.rand(2,3)
tensor = torch.rand(2,3)

In [12]:
numpy_tensor = torch.from_numpy(array)

In [13]:
numpy_tensor

tensor([[0.2721, 0.9106, 0.8654],
        [0.4522, 0.5215, 0.5769]], dtype=torch.float64)

In [16]:
RANDOM_SEED = 42

torch.manual_seed(seed= RANDOM_SEED)
tensor_A = torch.rand(3,2)

torch.manual_seed(seed = RANDOM_SEED)
tensor_B = torch.rand(3,2)

tensor_A == tensor_B

tensor([[True, True],
        [True, True],
        [True, True]])

In [18]:
#not same when changed the manual_seed (seed)

In [19]:
RANDOM_SEED = 42

torch.manual_seed(seed= RANDOM_SEED)
tensor_A = torch.rand(3,2)

# torch.manual_seed(seed = RANDOM_SEED) seeing by commenting the line
tensor_B = torch.rand(3,2)

tensor_A == tensor_B

tensor([[False, False],
        [False, False],
        [False, False]])

In [21]:
torch.cuda.is_available()

False

In [24]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [25]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [26]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [28]:
#moving to gpu
# i dont have gpu pls sponsor :)

In [29]:
nparray = np.array([1,2,3])
tensor_from_numpy = torch.from_numpy(nparray)

In [30]:
tensor_from_numpy

tensor([1, 2, 3])